@api = http://localhost:4000/products

GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
    "name": "microphone",
    "description": "microphone Sony"
}

### getting a product
GET {{api}}/2

### deleting a product
DELETE {{api}}/5

### get total products
GET {{api}}/count